" Name:         DawnBlush
" Description:  A fusion of dark dawns and blush tones
" Author:       Shurjo <mail@shurjo.me>
" Maintainer:   Shurjo <mail@shurjo.me>
" Website:      https://shurjo.me
" License:      Vim License (see `:help license`)
" Last Updated: Wed Jul 10 18:20:16 2024

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'dawnblush'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link CurSearch IncSearch
hi! link diffAdded DiffAdd
hi! link diffChanged DiffChange
hi! link diffRemoved DiffDelete
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link WildMenu IncSearch
hi! link markdownH1Delimiter markdownH1
hi! link markdownH2Delimiter markdownH2
hi! link markdownH3Delimiter markdownH3
hi! link markdownH4Delimiter markdownH4
hi! link markdownH5Delimiter markdownH5
hi! link markdownH6Delimiter markdownH6
hi! link markdownURL markdownLinkText
hi! link mkdLink mkdInlineURL
hi! link mkdLinkDef mkdInlineURL
hi! link mkdURL mkdInlineURL

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#242019', '#bc776c', '#8292a7', '#a59481', '#96a982', '#9182a6', '#a68295', '#a19a91', '#716c66', '#bc776c', '#8292a7', '#a59481', '#96a982', '#9182a6', '#a68295', '#a19a91']
endif
if get(g:,'disable_bg',0)
  hi Normal guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
  hi NormalNC guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#a19a91 guibg=#15130f gui=NONE cterm=NONE
  hi NormalNC guifg=#a19a91 guibg=#15130f gui=NONE cterm=NONE
  hi SignColumn guifg=#a19a91 guibg=#15130f gui=NONE cterm=NONE
  hi StatusLineNC guifg=#615c57 guibg=#15130f gui=NONE cterm=NONE
endif
if get(g:,'disable_float_bg',0)
  hi DarkenedPanel guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DarkenedStatusline guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Folded guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi DarkenedPanel guifg=NONE guibg=#1e1b15 gui=NONE cterm=NONE
  hi DarkenedStatusline guifg=NONE guibg=#1e1b15 gui=NONE cterm=NONE
  hi Folded guifg=#a19a91 guibg=#1e1b15 gui=NONE cterm=NONE
  hi NormalFloat guifg=#a19a91 guibg=#1e1b15 gui=NONE cterm=NONE
  hi Pmenu guifg=#716c66 guibg=#1e1b15 gui=NONE cterm=NONE
  hi StatusLine guifg=#716c66 guibg=#1e1b15 gui=NONE cterm=NONE
  hi TabLine guifg=#716c66 guibg=#1e1b15 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#1e1b15 gui=NONE cterm=NONE
endif
if !s:italics 
  hi Comment guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
else
  hi Comment guifg=#615c57 guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
endif
hi ColorColumn guifg=NONE guibg=#242019 gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#0f0d0b gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#0f0d0b gui=NONE cterm=NONE
hi CursorLineNr guifg=#a59481 guibg=#0f0d0b gui=NONE cterm=NONE
hi DiffAdd guifg=NONE guibg=#333c48 gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#242019 gui=NONE cterm=NONE
hi DiffDelete guifg=NONE guibg=#43293a gui=NONE cterm=NONE
hi DiffText guifg=NONE guibg=#433842 gui=NONE cterm=NONE
hi Directory guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi netrwClassify guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#bc776c guibg=NONE gui=bold cterm=bold
hi FloatBorder guifg=#2c2b27 guibg=NONE gui=NONE cterm=NONE
hi FloatTitle guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
hi FoldColumn guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
hi IncSearch guifg=#15130f guibg=#a68295 gui=NONE cterm=NONE
hi LineNr guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
hi MatchParen guifg=#a19a91 guibg=#2c2b27 gui=NONE cterm=NONE
hi ModeMsg guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#615c57 guibg=NONE gui=NONE cterm=NONE
hi PmenuSbar guifg=NONE guibg=#0f0d0b gui=NONE cterm=NONE
hi PmenuSel guifg=#a19a91 guibg=#242019 gui=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#2c2b27 gui=NONE cterm=NONE
hi Question guifg=#a59481 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=NONE guibg=#2c2b27 gui=NONE cterm=NONE
hi SpecialKey guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#716c66 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#716c66 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#716c66 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#716c66 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi TabLineSel guifg=#a19a91 guibg=#242019 gui=NONE cterm=NONE
hi Title guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
hi VertSplit guifg=#2c2b27 guibg=NONE gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#2c2b27 gui=NONE cterm=NONE
hi WarningMsg guifg=#a59481 guibg=NONE gui=NONE cterm=NONE
hi Boolean guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#a59481 guibg=NONE gui=NONE cterm=NONE
hi Conditional guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi Constant guifg=#a59481 guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi Define guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#bc776c guibg=NONE gui=NONE cterm=NONE
hi Exception guifg=#6c8fbc guibg=NONE gui=NONE cterm=NONE
hi Float guifg=#a59481 guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#d16757 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#bc776c guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi Macro guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#6c8fbc guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi PreCondit guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Repeat guifg=#6c8fbc guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#bc976c guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi Tag guifg=#a68295 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi Typedef guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi pythonBuiltin guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi htmlArg guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi htmlBold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
hi htmlEndTag guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi htmlH1 guifg=#9182a6 guibg=NONE gui=bold cterm=bold
hi htmlH2 guifg=#96a982 guibg=NONE gui=bold cterm=bold
hi htmlH3 guifg=#bc776c guibg=NONE gui=bold cterm=bold
hi htmlH4 guifg=#a59481 guibg=NONE gui=bold cterm=bold
hi htmlH5 guifg=#8292a7 guibg=NONE gui=bold cterm=bold
if !s:italics 
  hi htmlItalic guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi htmlItalic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi htmlItalic gui=NONE cterm=NONE
  endif
endif
hi htmlLink guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi htmlTag guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi htmlTagN guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
hi htmlTagName guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi markdownDelimiter guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi markdownH1 guifg=#9182a6 guibg=NONE gui=bold cterm=bold
hi markdownH2 guifg=#96a982 guibg=NONE gui=bold cterm=bold
hi markdownH3 guifg=#bc776c guibg=NONE gui=bold cterm=bold
hi markdownH4 guifg=#a59481 guibg=NONE gui=bold cterm=bold
hi markdownH5 guifg=#8292a7 guibg=NONE gui=bold cterm=bold
hi markdownH6 guifg=#96a982 guibg=NONE gui=bold cterm=bold
hi markdownLinkText guifg=#9182a6 guibg=NONE gui=underline cterm=underline
if !s:italics 
  hi mkdCode guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
else
  hi mkdCode guifg=#96a982 guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi mkdCode gui=NONE cterm=NONE
  endif
endif
hi mkdCodeDelimiter guifg=#bc776c guibg=NONE gui=NONE cterm=NONE
hi mkdCodeEnd guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi mkdCodeStart guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi mkdFootnotes guifg=#96a982 guibg=NONE gui=NONE cterm=NONE
hi mkdID guifg=#96a982 guibg=NONE gui=underline cterm=underline
hi mkdInlineURL guifg=#9182a6 guibg=NONE gui=underline cterm=underline
hi mkdListItemLine guifg=#a19a91 guibg=NONE gui=NONE cterm=NONE
hi mkdRule guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi VimwikiHR guifg=#716c66 guibg=NONE gui=NONE cterm=NONE
hi VimwikiHeader1 guifg=#9182a6 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader2 guifg=#96a982 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader3 guifg=#a68295 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader4 guifg=#a59481 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader5 guifg=#8292a7 guibg=NONE gui=bold cterm=bold
hi VimwikiHeader6 guifg=#96a982 guibg=NONE gui=bold cterm=bold
hi VimwikiHeaderChar guifg=#8292a7 guibg=NONE gui=NONE cterm=NONE
hi VimwikiLink guifg=#9182a6 guibg=NONE gui=underline cterm=underline
hi VimwikiList guifg=#9182a6 guibg=NONE gui=NONE cterm=NONE
hi VimwikiNoExistsLink guifg=#bc776c guibg=NONE gui=NONE cterm=NONE

if s:t_Co >= 256
  if get(g:,'disable_bg',0)
    hi Normal ctermfg=247 ctermbg=NONE cterm=NONE
    hi NormalNC ctermfg=247 ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=247 ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermfg=59 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=247 ctermbg=233 cterm=NONE
    hi NormalNC ctermfg=247 ctermbg=233 cterm=NONE
    hi SignColumn ctermfg=247 ctermbg=233 cterm=NONE
    hi StatusLineNC ctermfg=59 ctermbg=233 cterm=NONE
  endif
  if get(g:,'disable_float_bg',0)
    hi DarkenedPanel ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DarkenedStatusline ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Folded ctermfg=247 ctermbg=NONE cterm=NONE
    hi NormalFloat ctermfg=247 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=242 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=242 ctermbg=NONE cterm=NONE
    hi TabLine ctermfg=242 ctermbg=NONE cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi DarkenedPanel ctermfg=NONE ctermbg=234 cterm=NONE
    hi DarkenedStatusline ctermfg=NONE ctermbg=234 cterm=NONE
    hi Folded ctermfg=247 ctermbg=234 cterm=NONE
    hi NormalFloat ctermfg=247 ctermbg=234 cterm=NONE
    hi Pmenu ctermfg=242 ctermbg=234 cterm=NONE
    hi StatusLine ctermfg=242 ctermbg=234 cterm=NONE
    hi TabLine ctermfg=242 ctermbg=234 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=234 cterm=NONE
  endif
  if !s:italics 
    hi Comment ctermfg=59 ctermbg=NONE cterm=NONE
  else
    hi Comment ctermfg=59 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  hi ColorColumn ctermfg=NONE ctermbg=234 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=232 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=232 cterm=NONE
  hi CursorLineNr ctermfg=137 ctermbg=232 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=234 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=237 cterm=NONE
  hi Directory ctermfg=139 ctermbg=NONE cterm=NONE
  hi netrwClassify ctermfg=103 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=174 ctermbg=NONE cterm=bold
  hi FloatBorder ctermfg=235 ctermbg=NONE cterm=NONE
  hi FloatTitle ctermfg=59 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=59 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=233 ctermbg=139 cterm=NONE
  hi LineNr ctermfg=59 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=247 ctermbg=235 cterm=NONE
  hi ModeMsg ctermfg=242 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=103 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=59 ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=232 cterm=NONE
  hi PmenuSel ctermfg=247 ctermbg=234 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=235 cterm=NONE
  hi Question ctermfg=137 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=235 cterm=NONE
  hi SpecialKey ctermfg=108 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi TabLineSel ctermfg=247 ctermbg=234 cterm=NONE
  hi Title ctermfg=247 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=235 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=235 cterm=NONE
  hi WarningMsg ctermfg=137 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=139 ctermbg=NONE cterm=NONE
  hi Character ctermfg=137 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=139 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=137 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=139 ctermbg=NONE cterm=NONE
  hi Define ctermfg=103 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi Error ctermfg=174 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=67 ctermbg=NONE cterm=NONE
  hi Float ctermfg=137 ctermbg=NONE cterm=NONE
  hi Function ctermfg=167 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=174 ctermbg=NONE cterm=NONE
  hi Include ctermfg=103 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=139 ctermbg=NONE cterm=NONE
  hi Label ctermfg=108 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=103 ctermbg=NONE cterm=NONE
  hi Number ctermfg=67 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=242 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=103 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=103 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=67 ctermbg=NONE cterm=NONE
  hi Special ctermfg=139 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=139 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=103 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=139 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=108 ctermbg=NONE cterm=NONE
  hi String ctermfg=137 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=108 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=139 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=103 ctermbg=NONE cterm=NONE
  hi Type ctermfg=108 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=108 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi pythonBuiltin ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlEndTag ctermfg=242 ctermbg=NONE cterm=NONE
  hi htmlH1 ctermfg=103 ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=108 ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=174 ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=137 ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=67 ctermbg=NONE cterm=bold
  if !s:italics 
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
    if !s:italics
      hi htmlItalic cterm=NONE
    endif
  endif
  hi htmlLink ctermfg=103 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=242 ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=247 ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=108 ctermbg=NONE cterm=NONE
  hi markdownDelimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi markdownH1 ctermfg=103 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=108 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=174 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=137 ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=67 ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=108 ctermbg=NONE cterm=bold
  hi markdownLinkText ctermfg=103 ctermbg=NONE cterm=underline
  if !s:italics 
    hi mkdCode ctermfg=108 ctermbg=NONE cterm=NONE
  else
    hi mkdCode ctermfg=108 ctermbg=NONE cterm=italic
    if !s:italics
      hi mkdCode cterm=NONE
    endif
  endif
  hi mkdCodeDelimiter ctermfg=174 ctermbg=NONE cterm=NONE
  hi mkdCodeEnd ctermfg=108 ctermbg=NONE cterm=NONE
  hi mkdCodeStart ctermfg=108 ctermbg=NONE cterm=NONE
  hi mkdFootnotes ctermfg=108 ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=108 ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=103 ctermbg=NONE cterm=underline
  hi mkdListItemLine ctermfg=247 ctermbg=NONE cterm=NONE
  hi mkdRule ctermfg=242 ctermbg=NONE cterm=NONE
  hi VimwikiHR ctermfg=242 ctermbg=NONE cterm=NONE
  hi VimwikiHeader1 ctermfg=103 ctermbg=NONE cterm=bold
  hi VimwikiHeader2 ctermfg=108 ctermbg=NONE cterm=bold
  hi VimwikiHeader3 ctermfg=139 ctermbg=NONE cterm=bold
  hi VimwikiHeader4 ctermfg=137 ctermbg=NONE cterm=bold
  hi VimwikiHeader5 ctermfg=67 ctermbg=NONE cterm=bold
  hi VimwikiHeader6 ctermfg=108 ctermbg=NONE cterm=bold
  hi VimwikiHeaderChar ctermfg=67 ctermbg=NONE cterm=NONE
  hi VimwikiLink ctermfg=103 ctermbg=NONE cterm=underline
  hi VimwikiList ctermfg=103 ctermbg=NONE cterm=NONE
  hi VimwikiNoExistsLink ctermfg=174 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: base           #15130f ~
" Color: surface        #1e1b15 ~
" Color: overlay        #242019 ~
" Color: muted          #615c57 ~
" Color: subtle         #716c66 ~
" Color: text           #a19a91 ~
" Color: red            #bc776c ~
" Color: yellow         #a59481 ~
" Color: pink           #a68295 ~
" Color: blue           #8292a7 ~
" Color: green          #96a982 ~
" Color: purple         #9182a6 ~
" Color: brightred      #d16757 ~
" Color: brightyellow   #bc976c ~
" Color: brightpink     #bd6b97 ~
" Color: brightblue     #6c8fbc ~
" Color: brightgreen    #98bc6c ~
" Color: brightpurple   #8d6cbc ~
" Color: highlight_low  #0f0d0b ~
" Color: highlight_med  #2c2b27 ~
" Color: highlight_high #44423f ~
" Color: diff_add       #333c48 ~
" Color: diff_delete    #43293a ~
" Color: diff_text      #433842 ~
" Term colors: overlay red blue yellow
" Term colors: green   purple pink text
" Term colors: subtle  red blue yellow
" Term colors: green   purple pink text
" vim: et ts=8 sw=2 sts=2
